export const video = {id: '00000000-0000-4000-8000-000000000001', source_filename: 'Vector lesson.mp4', source_type: 'upload', status: 'ready', created_at: '2026-10-01T12:00:00Z'};
export const secondVideo = {...video, id: '00000000-0000-4000-8000-000000000002', source_filename: 'Second lesson.mp4'};
export const uploadedVideo = {...video, id: '00000000-0000-4000-8000-000000000003', source_filename: 'My lesson.mp4', status: 'queued'};
export const segments = [{segment_index: 0, start_s: 0, end_s: 5, text: 'Multiply matching coordinates, then add the products.'}, {segment_index: 1, start_s: 6, end_s: 10, text: 'If one vector is zero, its dot product is zero but its angle is undefined.'}];
const common = {video_id: video.id, subtitle: 'A small model you can check against the source.', coverage: {kind: 'excerpt', start_s: 0, end_s: 10, gaps: ['Fixture content for browser tests; this is not a real lecture.']}, sources: [{id: 'definition', kind: 'transcript', start_s: 0, end_s: 5, summary: 'Coordinate rule.'}, {id: 'boundary', kind: 'frame', start_s: 6, end_s: 10, summary: 'Zero-vector boundary.'}], sections: [], cards: [], slides: [], playground: null};
export const guide = {...common, kind: 'study-guide', title: 'Dot products, made tangible', sections: [{title: 'Two ways to see the same operation', origin: 'lecture', paragraphs: ['The dot product multiplies matching coordinates and adds the products. In two dimensions, v · w = vₓwₓ + vᵧwᵧ.'], bullets: ['A positive result indicates similar direction for two nonzero vectors.', 'A negative result indicates opposing direction.', 'Zero vectors need a separate angle check.'], citations: ['definition', 'boundary']}, {title: 'Try a prediction', origin: 'generated', paragraphs: ['For v = (3, 4) and w = (2, 0), predict the result. Then change only the first coordinate of v.'], bullets: [], citations: ['definition']}]};
export const cards = {...common, kind: 'flashcards', title: 'A little retrieval practice', cards: [{front: 'What is (3, 4) · (2, 0)?', back: '6', origin: 'generated', rationale: '3 × 2 + 4 × 0 = 6.', hint: 'Multiply matching coordinates.', tags: ['vectors'], citations: ['definition']}, {front: 'Does a zero dot product always imply a right angle?', back: 'No. The zero vector has no defined angle.', origin: 'lecture', rationale: '', hint: '', tags: ['boundaries'], citations: ['boundary']}]};
export const playground = {...common, kind: 'playground', title: 'Change one thing. Notice what moves.', playground: {model: 'dot-product-2d', question: 'How does direction change the dot product?', initial: {v: [3, 4], w: [2, 0]}, model_limit: 'Exact arithmetic for two vectors in two dimensions; not a learned simulation.', extension_note: 'Generated practice applies the cited coordinate rule.', citations: ['definition', 'boundary']}};
export const presentation = {...common, kind: 'presentation', title: 'Teach the idea in two steps', slides: [{title: 'The coordinate rule', bullets: ['Multiply matching coordinates.', 'Add the products.', 'Check (3, 4) · (2, 0).'], notes: 'Pause for a prediction. This computed example gives 6.', origin: 'generated', citations: ['definition']}, {title: 'The useful exception', bullets: ['A zero dot product can include a zero vector.', 'The angle of a zero vector is undefined.'], notes: 'Use the Playground zero-vector example to make the boundary visible.', origin: 'lecture', citations: ['boundary']}]};
export const reviewedCases = {...playground, title: 'Compare assumptions explicitly', playground: {model: 'reviewed-cases', question: 'Does zero dot product imply a right angle?', model_limit: 'Two reviewed cases, not a general simulation.', extension_note: 'Generated comparison based on the definition.', controls: [{id: 'nonzero', label: 'Both vectors nonzero', options: [{id: 'yes', label: 'Yes'}, {id: 'no', label: 'No'}]}], cases: [{when: {nonzero: 'yes'}, title: 'Both vectors are nonzero', outcome: 'The angle is 90 degrees.', explanation: 'A nonzero product of norms allows division in the angle formula.', assumptions: ['Dot product is zero.'], unknowns: [], citations: ['definition']}, {when: {nonzero: 'no'}, title: 'One vector is zero', outcome: 'The angle is undefined.', explanation: 'The product of norms is zero.', assumptions: ['At least one vector is zero.'], unknowns: ['No angle is defined for that vector.'], citations: ['boundary']}]}};
export const mediaOrigin = 'https://storage.example.test';
export const config = {media_origin: mediaOrigin, max_upload_bytes: 1000000, transcript_units: 1, frame_thumb_units: 1};
export function toolResult(structuredContent, privateData = {}) { return {content: [{type: 'text', text: 'Fixture host response.'}], structuredContent, _meta: {vmf: {config, ...privateData}}}; }
