"""Database modules (Supabase PostgreSQL)."""

from src.db.supabase import (
    apply_billing_credit_grant,
    claim_next_video_job,
    complete_video_job,
    consume_processing_credit,
    count_videos_for_user,
    create_video,
    enqueue_video_job,
    get_client,
    get_credits,
    get_video,
    get_video_job,
    has_unlimited_video_access,
    list_queued_video_jobs,
    list_stale_processing_video_jobs,
    reset_client,
    list_videos,
    requeue_video_job,
    update_credits,
    update_video_status,
)

__all__ = [
    "claim_next_video_job",
    "complete_video_job",
    "consume_processing_credit",
    "count_videos_for_user",
    "get_client",
    "create_video",
    "enqueue_video_job",
    "get_video",
    "get_video_job",
    "has_unlimited_video_access",
    "list_queued_video_jobs",
    "list_stale_processing_video_jobs",
    "reset_client",
    "update_video_status",
    "list_videos",
    "requeue_video_job",
    "get_credits",
    "update_credits",
    "apply_billing_credit_grant",
]
